"""
Patch Generator for Inception-of-Context (IoC) Part 3: Generation, Application, and Validation Loop.
Prompts the local Ollama LLM to generate structured JSON patches strictly conforming to Subject VI.3.
Handles robust JSON extraction, schema enforcement, and error-feedback retry prompting.
"""

import json
import os
import re
import sys
from typing import Any, Dict, List, Optional

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from p2.llm import OllamaClient  # noqa: E402


PATCH_SYSTEM_PROMPT = """You are an autonomous AI software engineer.
Your task is to write code modifications by generating a SINGLE structured JSON patch.

CRITICAL RULES:
1. Output ONLY valid, raw JSON. Do NOT include markdown code fences (no ```json, no ```py), explanations, or conversational notes.
2. The patch must NEVER be a unified diff or git diff.
3. For "modify" operations, the "content" field MUST contain the COMPLETE post-change file content.
4. JSON ESCAPING: The "content" value must be a single valid JSON string. Inside Python code in "content", prefer single quotes '...' for strings (e.g. f'{val:.2f}'), or escape double quotes as \\". Never put markdown fences inside "content".
5. Do NOT define stub functions whose body is only 'pass', '...', or 'return None'. Write full, working implementations.
6. Do NOT include any prompt markers (e.g. '=== RETRIEVED CHUNK ===') in the code content.
7. Touch a MAXIMUM of 3 files at once.
8. Schema:
{
  "summary": "Clear description of changes made",
  "files": [
    {
      "path": "relative/path/to/file.py",
      "op": "create | modify | delete",
      "content": "complete file content as a string"
    }
  ]
}"""


def extract_json_patch(raw_text: str) -> Dict[str, Any]:
    """
    Safely extract and parse JSON patch from LLM output.
    Handles markdown fences (```json ... ```), trailing commas, or surrounding text.
    """
    text = raw_text.strip()

    # 1. Remove markdown code fences if present
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()

    # 2. Try direct parsing with strict=False
    try:
        data = json.loads(text, strict=False)
        if isinstance(data, dict) and "files" in data:
            return data
    except Exception:
        pass

    # 3. Find outermost JSON object { ... }
    first_brace = text.find("{")
    last_brace = text.rfind("}")
    if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
        json_candidate = text[first_brace : last_brace + 1]
        try:
            data = json.loads(json_candidate, strict=False)
            if isinstance(data, dict) and "files" in data:
                return data
        except Exception:
            pass

        # 4. Attempt repair of Python-style adjacent string concatenation: "..." \n "..."
        try:
            repaired = re.sub(r'"\s*\n\s*"', r"\\n", json_candidate)
            data = json.loads(repaired, strict=False)
            if isinstance(data, dict) and "files" in data:
                return data
        except Exception:
            pass

    # 5. Regex-based resilient fallback extraction (handles inner braces, f-strings, unescaped quotes)
    try:
        sum_m = re.search(r'"summary"\s*:\s*"([^"]+)"', text)
        summary = sum_m.group(1) if sum_m else "Patch generated by local LLM"

        file_pattern = re.compile(
            r'\{\s*"path"\s*:\s*"([^"]+)"\s*,\s*"op"\s*:\s*"([^"]+)"\s*,\s*"content"\s*:\s*([\s\S]+?)\s*\}\s*(?=\s*,\s*\{\s*"path"|\s*\])',
            re.DOTALL,
        )
        matches = list(file_pattern.finditer(text))
        if matches:
            file_entries: List[Dict[str, Any]] = []
            for m in matches:
                p, op, c = m.groups()
                c = c.strip()
                if c.startswith('"') and c.endswith('"'):
                    c = c[1:-1]
                # Strip markdown fences if LLM wrapped code
                c = re.sub(r"^```(?:[a-zA-Z0-9_\-]+)?\s*", "", c)
                c = re.sub(r"\s*```$", "", c)
                c = c.replace('\\n', '\n').replace('\\t', '\t').replace('\\"', '"')
                file_entries.append({"path": p, "op": op, "content": c})

            if file_entries:
                return {"summary": summary, "files": file_entries}
    except Exception:
        pass

    raise ValueError(f"Could not parse a valid structured JSON patch from LLM output:\n{raw_text[:300]}...")


class PatchGenerator:
    """
    Generates structured JSON patches using the local Ollama LLM.
    Supports iterative error-feedback prompting for the validation retry loop.
    """

    def __init__(self, llm_client: OllamaClient, target_dir: str) -> None:
        self.llm_client = llm_client
        self.target_dir = os.path.abspath(target_dir)

    def build_prompt(
        self,
        intent: str,
        context_chunks: List[Dict[str, Any]],
        error_feedback: Optional[str] = None,
        previous_patch: Optional[Dict[str, Any]] = None,
        attempt: int = 1,
    ) -> str:
        """
        Assemble the user prompt for the coder LLM.
        Includes project context chunks, the user intent, and any validation/sanity errors.
        """
        sections: List[str] = []

        # 1. Context Chunks from the Codebase
        if context_chunks:
            sections.append("=== RELEVANT CODEBASE CONTEXT ===")
            for idx, c in enumerate(context_chunks, 1):
                fpath = c.get("file_path", "")
                sym = c.get("symbol_name", "")
                s_line = c.get("start_line", "")
                e_line = c.get("end_line", "")
                content = c.get("content", "").strip()
                sections.append(
                    f"--- File: {fpath} | Symbol: {sym} (Lines {s_line}-{e_line}) ---\n"
                    f"{content}\n"
                )

        # 2. Existing File Contents for Context (if modifying files)
        # Inspect target directory files mentioned in context
        seen_files = {c.get("file_path") for c in context_chunks if c.get("file_path")}
        existing_files_text: List[str] = []
        for rel_path in seen_files:
            full_path = os.path.join(self.target_dir, rel_path)
            if os.path.isfile(full_path):
                try:
                    with open(full_path, "r", encoding="utf-8", errors="replace") as f:
                        file_text = f.read()
                    existing_files_text.append(
                        f"=== EXISTING CURRENT CONTENT OF: {rel_path} ===\n"
                        f"{file_text}\n"
                    )
                except Exception:
                    pass

        if existing_files_text:
            sections.extend(existing_files_text)

        # 3. User Coding Intent
        sections.append(
            f"=== USER CODING INTENT ===\n"
            f"{intent}\n"
        )

        # 4. Error Feedback (for Retry Loop attempts 2 and 3)
        if error_feedback:
            sections.append(
                f"=== PREVIOUS ATTEMPT FAILED (ATTEMPT {attempt - 1}) ===\n"
                f"Your previous patch produced the following validation or sanity errors:\n"
                f"{error_feedback}\n\n"
                f"CRITICAL: You MUST correct these specific errors in this attempt. "
                f"Do not repeat the same mistake. Output the corrected, complete JSON patch."
            )

        # 5. Output Instructions
        sections.append(
            "=== OUTPUT FORMAT ===\n"
            "Return ONLY the JSON object conforming to the schema:\n"
            '{\n  "summary": "...",\n  "files": [{"path": "...", "op": "modify", "content": "..."}]\n}'
        )

        return "\n\n".join(sections)

    async def generate_patch(
        self,
        intent: str,
        context_chunks: List[Dict[str, Any]],
        error_feedback: Optional[str] = None,
        previous_patch: Optional[Dict[str, Any]] = None,
        attempt: int = 1,
    ) -> Dict[str, Any]:
        """
        Send prompt to local Ollama and return the parsed JSON patch dictionary.
        """
        prompt = self.build_prompt(
            intent=intent,
            context_chunks=context_chunks,
            error_feedback=error_feedback,
            previous_patch=previous_patch,
            attempt=attempt,
        )

        # Low temperature for deterministic JSON output and syntax correctness
        raw_response = await self.llm_client.generate(
            prompt=prompt,
            system=PATCH_SYSTEM_PROMPT,
            temperature=0.1,
        )

        patch = extract_json_patch(raw_response)
        return patch

    def generate_patch_sync(
        self,
        intent: str,
        context_chunks: List[Dict[str, Any]],
        error_feedback: Optional[str] = None,
        previous_patch: Optional[Dict[str, Any]] = None,
        attempt: int = 1,
    ) -> Dict[str, Any]:
        """Synchronous wrapper for generate_patch."""
        prompt = self.build_prompt(
            intent=intent,
            context_chunks=context_chunks,
            error_feedback=error_feedback,
            previous_patch=previous_patch,
            attempt=attempt,
        )
        raw_response = self.llm_client.generate_sync(
            prompt=prompt,
            system=PATCH_SYSTEM_PROMPT,
            temperature=0.1,
        )
        return extract_json_patch(raw_response)
